// console.log(50 * 2);
// console.log(100 / 4);
// console.log(10 + 20);
// console.log(30 - 5);
// console.log(2 ** 3);
// console.log(15 % 4);
// console.log(10 > 5);
// console.log(3 < 7);
// console.log(5 === 5);
// console.log(10 !== 5);
// console.log(10 >= 10);
// console.log(5 <= 3);
// console.log(true && false);
// console.log(true || false);
// console.log(!true);

// console.log(true || true);
// console.log(false || true);
// console.log(false && true);

console.log(!true);
console.log(!!false);
console.log(false && false);
console.log(true && true);
console.log(false && true);
console.log(false || false);
console.log(false || true);
console.log(true || false);
console.log(!false || (false && true));
console.log(!(false || true) && false);
